### PR TITLE
Changed the colours

### PR DESCRIPTION
**Pull request by tejasvisoi**
In reference to issue relating to colors.xml

### CODE REVIEW

**Comment by namantechlabs** [comment]
ngl, these colours are pretty bad. @rachittt you should mark this PR as invalid.

**Comment by oorjitchowdhary** [comment]
@tejasvisoi you could perhaps also add a fixes/resolves #3 in order for best management of the repository.

**Comment by rachittt** [comment]
fixes #3

**Comment by rachittt** [comment]
closes #3

**Comment by ribhavsharma** [comment]
i think create NEW

**Pull request merged**
